{% set version = "1.4.2" %}
{% set eccodes_version = "2.26.0" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 4049268d58ba2a87574c23e06b1539cb314944a7b75efbd4cd0efc95e4cfe474

build:
  number: 1
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cffi
    - findlibs
    - eccodes >={{ eccodes_version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - findlibs
    - attrs
    - eccodes >={{ eccodes_version }}

test:
  imports:
    - eccodes
    - gribapi
    - gribapi._bindings  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017- ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
    - dtip
    - iainrussell
    - shahramn
