{% set version = "2.1.0" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  fn: eccodes-{{ version }}-Source.tar.gz
  sha256: e7382b06d99e9f6558751c888403181cbbac95ea51275c7ff8d41c15c2ccf554

build:
  number: 1
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python
    - numpy x.x
    - boost 1.63.*
    - jasper
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - perl
    - eccodes {{ version }}
  run:
    - python
    - numpy x.x
    - jasper
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - eccodes {{ version }}

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2017 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
