{% set version = "2.5.0" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: 18ab44bc444168fd324d07f7dea94f89e056f5c5cd973e818c8783f952702e4e

build:
  number: 2
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python
    - numpy 1.8.*
    - boost 1.65.1
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf 4.4.*
    - hdf5 1.10.1
    - perl 5.22.2.1
    - eccodes {{ version }}
  run:
    - python
    - numpy >=1.8
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf 4.4.*
    - hdf5 1.10.1
    - eccodes {{ version }}

test:
  imports:
    - eccodes
    - gribapi
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2017 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
