{% set version = "1.7.0" %}
# See https://github.com/ecmwf/eccodes-python/blob/{{ version }}/gribapi/__init__.py#L17
{% set eccodes_version = "2.31.0" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 68227124c5f88ff6c8f345779e9e058dfd086b4a966cf615a4f8b28cdcc1e3cc

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - cffi
    - findlibs
    - eccodes >={{ eccodes_version }}
  run:
    - python
    - cffi
    - findlibs
    - attrs
    - eccodes >={{ eccodes_version }}

test:
  imports:
    - eccodes
    - gribapi
    - gribapi._bindings  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017- ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
    - dtip
    - iainrussell
    - shahramn
    - xylar
    - zklaus
