{% set version = "2021.03.0" %}
{% set eccodes_version = "2.16" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 7251436ddc20bded9a96408c705360d282918f2a6003dee05457b62d962b8491

build:
  number: 0
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cffi
    - eccodes >={{ eccodes_version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - attrs
    - eccodes >={{ eccodes_version }}

test:
  imports:
    - eccodes
    - gribapi
    - gribapi._bindings  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017- ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
    - dtip
    - shahramn
