{% set version = "2.12.3" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/131371724/eccodes-{{ version }}-Source.tar.gz
  sha256: 6dafe2fe3a9994ab2359f8bf8f6bad04dc4f936918999cf01e026323882b6b77

build:
  number: 1001
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - boost
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - eccodes {{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - eccodes {{ version }}

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
