schema_version: 1

context:
  version: "2.47.0"

package:
  name: python-eccodes
  version: ${{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/${{ version }}.tar.gz
  sha256: 350291df04a4d517ab01584c1f38ca764178d52f6146f636323b681aa883c391

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - cffi
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - cffi
    - findlibs
    - eccodes >=${{ version }}
  run:
    - python
    - attrs
    - cffi
    - findlibs
    - eccodes >=${{ version }}

tests:
  - python:
      imports:
        - eccodes
        - gribapi
        - if: not win
          then: gribapi._bindings
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017- ECMWF.
  homepage: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  repository: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
    - dtip
    - iainrussell
    - shahramn
    - xylar
    - zklaus
