appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CRJzjSknuI/l4c4DCMlDts86df+rvJQchA4izXD9UbcAARo4QiNnX0829l2eh0ZMZ7HHTtz+DJt80P8Jm1NXU/FKcqpx/mqLKrRvyyjkQ5qdVDu1IBfgRpw825BkqsdLU9RnZFC2CmPxUpkQPRUhXpJCeZUsN+w+o/XSID7GB/CvAXqe5+2AfmB9oAJMD2JDpd+MheNyxEgTsPyiuh3zdAIGqzIHkz+dSJp06DO3udUSRiJoNDkNSsuKyPLTY573R6N/Z0sc53YCyV+dMKt9PxoQNxl/yGs7eH7X2zUrLXl7EjkepaHE7M9f8zfCWnD8lbiJLAnK3dadbDx1XpX2VhMQCylfzQGqrdAbw7BrWlNdAtY6xiMOSRBLMSIBKIFMNKGmtTabn9ozVz46pmqjLI9JAOW6hcvnu5HUZsBKvWxQ3+y/ZWJcJSI1eDonomd7WGGguJpYDNtNpqa7R4rUxGsBwPxeFbGACuqwroFnMzTusSZeefuQJw2QI0pGSS+mH/sC41p0vYVPJL0T4irIPjn1PH9mc/2Qo6BeYwIfMVGi+TXaXyGQ6DNKgbo5BsY7fRWz65utwOny/AxQHo3TpvIWYg8JGCblW+u0k/1EfewtYmYpfiq8MvydjBsKActSUCoKz8q4A8pCfqnhmAZN8hUH+SD0W7UefKTMtfXjsfM=}
